/**
 * Merchant Map for Rule-based Categorization
 *
 * Maps 500+ Indian merchant names, keywords, and UPI handles to categories.
 * Categories match the DB schema defined in seed.ts.
 */

export type CategoryName =
  | 'Food & Dining'
  | 'Transport'
  | 'Shopping'
  | 'Bills & Utilities'
  | 'Entertainment'
  | 'Health'
  | 'Education'
  | 'Income'
  | 'Investments'
  | 'Rent & EMI'
  | 'Groceries'
  | 'Others';

/**
 * HashMap of merchant/keyword -> category.
 * Keys are lowercase, no special characters.
 */
export const MERCHANT_CATEGORY_MAP: Record<string, CategoryName> = {
  // ============================
  // Food & Dining (80+ entries)
  // ============================
  swiggy: 'Food & Dining',
  zomato: 'Food & Dining',
  dominos: 'Food & Dining',
  dominospizza: 'Food & Dining',
  mcdonalds: 'Food & Dining',
  mcd: 'Food & Dining',
  kfc: 'Food & Dining',
  starbucks: 'Food & Dining',
  subway: 'Food & Dining',
  pizzahut: 'Food & Dining',
  burgerking: 'Food & Dining',
  chaipoint: 'Food & Dining',
  haldirams: 'Food & Dining',
  barbequenation: 'Food & Dining',
  barbeque: 'Food & Dining',
  behrouz: 'Food & Dining',
  faasos: 'Food & Dining',
  eatsure: 'Food & Dining',
  box8: 'Food & Dining',
  dunkin: 'Food & Dining',
  baskinrobbins: 'Food & Dining',
  naturals: 'Food & Dining',
  chaayos: 'Food & Dining',
  thirdwave: 'Food & Dining',
  bluetokai: 'Food & Dining',
  freshmenu: 'Food & Dining',
  restaurant: 'Food & Dining',
  cafe: 'Food & Dining',
  food: 'Food & Dining',
  dining: 'Food & Dining',
  biryani: 'Food & Dining',
  pizza: 'Food & Dining',
  burger: 'Food & Dining',
  taco: 'Food & Dining',
  noodles: 'Food & Dining',
  sushi: 'Food & Dining',
  bakery: 'Food & Dining',
  cake: 'Food & Dining',
  sweet: 'Food & Dining',
  mithai: 'Food & Dining',
  dhaba: 'Food & Dining',
  canteen: 'Food & Dining',
  mess: 'Food & Dining',
  tiffin: 'Food & Dining',
  lunch: 'Food & Dining',
  dinner: 'Food & Dining',
  breakfast: 'Food & Dining',
  snack: 'Food & Dining',
  tea: 'Food & Dining',
  coffee: 'Food & Dining',
  juice: 'Food & Dining',
  icecream: 'Food & Dining',
  wok: 'Food & Dining',
  grill: 'Food & Dining',
  tandoori: 'Food & Dining',
  mughlai: 'Food & Dining',
  chinese: 'Food & Dining',
  southindian: 'Food & Dining',
  dosa: 'Food & Dining',
  idli: 'Food & Dining',
  paratha: 'Food & Dining',
  thali: 'Food & Dining',
  chutneys: 'Food & Dining',
  paradise: 'Food & Dining',
  bikanervala: 'Food & Dining',
  saravana: 'Food & Dining',
  adyar: 'Food & Dining',
  sangeetha: 'Food & Dining',
  sagar: 'Food & Dining',
  udupi: 'Food & Dining',
  anjappar: 'Food & Dining',
  rajdhani: 'Food & Dining',
  mainland: 'Food & Dining',
  ohcalcutta: 'Food & Dining',
  socialoffline: 'Food & Dining',
  toit: 'Food & Dining',
  brewpub: 'Food & Dining',
  pub: 'Food & Dining',
  bar: 'Food & Dining',
  lounge: 'Food & Dining',
  eatfit: 'Food & Dining',
  rebel: 'Food & Dining',
  wendys: 'Food & Dining',
  papajohns: 'Food & Dining',
  tgif: 'Food & Dining',
  chilis: 'Food & Dining',

  // ============================
  // Transport (70+ entries)
  // ============================
  uber: 'Transport',
  ola: 'Transport',
  rapido: 'Transport',
  irctc: 'Transport',
  redbus: 'Transport',
  makemytrip: 'Transport',
  mmt: 'Transport',
  goibibo: 'Transport',
  cleartrip: 'Transport',
  yatra: 'Transport',
  indigo: 'Transport',
  airindia: 'Transport',
  spicejet: 'Transport',
  vistara: 'Transport',
  akasa: 'Transport',
  metro: 'Transport',
  dmrc: 'Transport',
  bmtc: 'Transport',
  nammametro: 'Transport',
  fastag: 'Transport',
  iocl: 'Transport',
  bpcl: 'Transport',
  hpcl: 'Transport',
  petrol: 'Transport',
  diesel: 'Transport',
  fuel: 'Transport',
  parking: 'Transport',
  toll: 'Transport',
  cab: 'Transport',
  taxi: 'Transport',
  auto: 'Transport',
  rickshaw: 'Transport',
  flight: 'Transport',
  airline: 'Transport',
  railway: 'Transport',
  train: 'Transport',
  bus: 'Transport',
  transport: 'Transport',
  travel: 'Transport',
  trip: 'Transport',
  booking: 'Transport',
  easemytrip: 'Transport',
  ixigo: 'Transport',
  abhibus: 'Transport',
  tsrtc: 'Transport',
  ksrtc: 'Transport',
  msrtc: 'Transport',
  upsrtc: 'Transport',
  rsrtc: 'Transport',
  apsrtc: 'Transport',
  meru: 'Transport',
  namma: 'Transport',
  drivezy: 'Transport',
  bounce: 'Transport',
  vogo: 'Transport',
  yulu: 'Transport',
  zoomcar: 'Transport',
  revv: 'Transport',
  savaari: 'Transport',
  gozo: 'Transport',
  shuttle: 'Transport',
  flybus: 'Transport',
  airvistara: 'Transport',
  goair: 'Transport',
  airasia: 'Transport',
  emirates: 'Transport',
  lufthansa: 'Transport',
  singapore: 'Transport',
  cathay: 'Transport',
  etihad: 'Transport',
  oyo: 'Transport',
  treebo: 'Transport',
  fabhotels: 'Transport',
  airbnb: 'Transport',
  zostel: 'Transport',

  // ============================
  // Shopping (70+ entries)
  // ============================
  amazon: 'Shopping',
  amzn: 'Shopping',
  flipkart: 'Shopping',
  myntra: 'Shopping',
  ajio: 'Shopping',
  meesho: 'Shopping',
  nykaa: 'Shopping',
  tatacliq: 'Shopping',
  reliancedigital: 'Shopping',
  croma: 'Shopping',
  snapdeal: 'Shopping',
  lenskart: 'Shopping',
  purplle: 'Shopping',
  pepperfry: 'Shopping',
  urbanladder: 'Shopping',
  firstcry: 'Shopping',
  decathlon: 'Shopping',
  shoppersstop: 'Shopping',
  shoppers: 'Shopping',
  lifestyle: 'Shopping',
  westside: 'Shopping',
  pantaloons: 'Shopping',
  zara: 'Shopping',
  hm: 'Shopping',
  uniqlo: 'Shopping',
  levis: 'Shopping',
  nike: 'Shopping',
  adidas: 'Shopping',
  puma: 'Shopping',
  reebok: 'Shopping',
  skechers: 'Shopping',
  bata: 'Shopping',
  woodland: 'Shopping',
  titan: 'Shopping',
  tanishq: 'Shopping',
  malabar: 'Shopping',
  kalyan: 'Shopping',
  joyalukkas: 'Shopping',
  reliance: 'Shopping',
  vijaysales: 'Shopping',
  poorvika: 'Shopping',
  sangeethamobiles: 'Shopping',
  apple: 'Shopping',
  samsung: 'Shopping',
  oneplus: 'Shopping',
  xiaomi: 'Shopping',
  realme: 'Shopping',
  ikea: 'Shopping',
  hometown: 'Shopping',
  fabindia: 'Shopping',
  global: 'Shopping',
  centralstore: 'Shopping',
  brandsfactory: 'Shopping',
  maxfashion: 'Shopping',
  fbb: 'Shopping',
  trends: 'Shopping',
  vmart: 'Shopping',
  vishal: 'Shopping',
  mall: 'Shopping',
  store: 'Shopping',
  retail: 'Shopping',
  clothing: 'Shopping',
  shoes: 'Shopping',
  electronics: 'Shopping',
  furniture: 'Shopping',
  jewellery: 'Shopping',
  jewelry: 'Shopping',
  cosmetics: 'Shopping',
  perfume: 'Shopping',
  watch: 'Shopping',
  eyewear: 'Shopping',
  luggage: 'Shopping',

  // ============================
  // Bills & Utilities (60+ entries)
  // ============================
  airtel: 'Bills & Utilities',
  jio: 'Bills & Utilities',
  vi: 'Bills & Utilities',
  vodafone: 'Bills & Utilities',
  bsnl: 'Bills & Utilities',
  tataplay: 'Bills & Utilities',
  tatasky: 'Bills & Utilities',
  dishtv: 'Bills & Utilities',
  d2h: 'Bills & Utilities',
  bescom: 'Bills & Utilities',
  msedcl: 'Bills & Utilities',
  tneb: 'Bills & Utilities',
  wbsedcl: 'Bills & Utilities',
  bses: 'Bills & Utilities',
  cesc: 'Bills & Utilities',
  torrent: 'Bills & Utilities',
  tpddl: 'Bills & Utilities',
  adani: 'Bills & Utilities',
  mahanagar: 'Bills & Utilities',
  igl: 'Bills & Utilities',
  gail: 'Bills & Utilities',
  hathway: 'Bills & Utilities',
  actfiber: 'Bills & Utilities',
  actfibernet: 'Bills & Utilities',
  electricity: 'Bills & Utilities',
  water: 'Bills & Utilities',
  gas: 'Bills & Utilities',
  phone: 'Bills & Utilities',
  mobile: 'Bills & Utilities',
  internet: 'Bills & Utilities',
  wifi: 'Bills & Utilities',
  broadband: 'Bills & Utilities',
  bill: 'Bills & Utilities',
  recharge: 'Bills & Utilities',
  dth: 'Bills & Utilities',
  postpaid: 'Bills & Utilities',
  prepaid: 'Bills & Utilities',
  landline: 'Bills & Utilities',
  piped: 'Bills & Utilities',
  cylinder: 'Bills & Utilities',
  lpg: 'Bills & Utilities',
  indane: 'Bills & Utilities',
  bharat: 'Bills & Utilities',
  mtnl: 'Bills & Utilities',
  pgvcl: 'Bills & Utilities',
  mgvcl: 'Bills & Utilities',
  dgvcl: 'Bills & Utilities',
  ugvcl: 'Bills & Utilities',
  uhbvn: 'Bills & Utilities',
  dhbvn: 'Bills & Utilities',
  jvvnl: 'Bills & Utilities',
  avvnl: 'Bills & Utilities',
  jdvvnl: 'Bills & Utilities',
  apspdcl: 'Bills & Utilities',
  tsspdcl: 'Bills & Utilities',
  tsnpdcl: 'Bills & Utilities',
  keb: 'Bills & Utilities',
  hescom: 'Bills & Utilities',
  mescom: 'Bills & Utilities',
  gescom: 'Bills & Utilities',
  chamundeshwari: 'Bills & Utilities',
  nbpdcl: 'Bills & Utilities',
  sbpdcl: 'Bills & Utilities',

  // ============================
  // Entertainment (50+ entries)
  // ============================
  netflix: 'Entertainment',
  hotstar: 'Entertainment',
  disney: 'Entertainment',
  spotify: 'Entertainment',
  jiocinema: 'Entertainment',
  amazonprime: 'Entertainment',
  prime: 'Entertainment',
  zee5: 'Entertainment',
  sonyliv: 'Entertainment',
  youtube: 'Entertainment',
  youtubepremium: 'Entertainment',
  bookmyshow: 'Entertainment',
  bms: 'Entertainment',
  pvr: 'Entertainment',
  inox: 'Entertainment',
  gaana: 'Entertainment',
  jiosaavn: 'Entertainment',
  wynk: 'Entertainment',
  movie: 'Entertainment',
  cinema: 'Entertainment',
  theatre: 'Entertainment',
  theater: 'Entertainment',
  concert: 'Entertainment',
  gaming: 'Entertainment',
  game: 'Entertainment',
  subscription: 'Entertainment',
  stream: 'Entertainment',
  playstation: 'Entertainment',
  xbox: 'Entertainment',
  steam: 'Entertainment',
  twitch: 'Entertainment',
  crunchyroll: 'Entertainment',
  mubi: 'Entertainment',
  aha: 'Entertainment',
  voot: 'Entertainment',
  mxplayer: 'Entertainment',
  altbalaji: 'Entertainment',
  eros: 'Entertainment',
  hungama: 'Entertainment',
  ludo: 'Entertainment',
  dream11: 'Entertainment',
  mpl: 'Entertainment',
  winzo: 'Entertainment',
  rummycircle: 'Entertainment',
  paytmfirst: 'Entertainment',
  applemu: 'Entertainment',
  audible: 'Entertainment',
  kindle: 'Entertainment',
  park: 'Entertainment',
  amusement: 'Entertainment',
  wonderla: 'Entertainment',
  imagica: 'Entertainment',
  museum: 'Entertainment',

  // ============================
  // Health (50+ entries)
  // ============================
  apollo: 'Health',
  practo: 'Health',
  onemg: 'Health',
  '1mg': 'Health',
  pharmeasy: 'Health',
  netmeds: 'Health',
  medplus: 'Health',
  maxhospital: 'Health',
  fortis: 'Health',
  manipal: 'Health',
  narayana: 'Health',
  cultfit: 'Health',
  cult: 'Health',
  healthifyme: 'Health',
  hospital: 'Health',
  doctor: 'Health',
  medical: 'Health',
  pharmacy: 'Health',
  medicine: 'Health',
  clinic: 'Health',
  dental: 'Health',
  dentist: 'Health',
  eye: 'Health',
  optical: 'Health',
  diagnostic: 'Health',
  lab: 'Health',
  pathology: 'Health',
  xray: 'Health',
  scan: 'Health',
  mri: 'Health',
  gym: 'Health',
  fitness: 'Health',
  yoga: 'Health',
  physiotherapy: 'Health',
  physio: 'Health',
  ayurveda: 'Health',
  homeopathy: 'Health',
  wellness: 'Health',
  spa: 'Health',
  massage: 'Health',
  thyrocare: 'Health',
  lal: 'Health',
  metropolis: 'Health',
  srl: 'Health',
  drreddy: 'Health',
  cipla: 'Health',
  sunpharma: 'Health',
  medanta: 'Health',
  kokilaben: 'Health',
  hinduja: 'Health',
  lilavati: 'Health',
  jaslok: 'Health',
  wockhardt: 'Health',
  nimhans: 'Health',
  aiims: 'Health',

  // ============================
  // Education (40+ entries)
  // ============================
  coursera: 'Education',
  udemy: 'Education',
  unacademy: 'Education',
  byjus: 'Education',
  vedantu: 'Education',
  upgrad: 'Education',
  simplilearn: 'Education',
  scaler: 'Education',
  skillshare: 'Education',
  linkedin: 'Education',
  school: 'Education',
  college: 'Education',
  university: 'Education',
  tuition: 'Education',
  course: 'Education',
  book: 'Education',
  library: 'Education',
  exam: 'Education',
  coaching: 'Education',
  institute: 'Education',
  academy: 'Education',
  tutorial: 'Education',
  class: 'Education',
  certification: 'Education',
  edx: 'Education',
  khanacademy: 'Education',
  whitehatjr: 'Education',
  cuemath: 'Education',
  toppr: 'Education',
  doubtnut: 'Education',
  testbook: 'Education',
  gradeup: 'Education',
  adda247: 'Education',
  oliveboard: 'Education',
  wifistudy: 'Education',
  neet: 'Education',
  jee: 'Education',
  gate: 'Education',
  cat: 'Education',
  ielts: 'Education',
  toefl: 'Education',

  // ============================
  // Investments (50+ entries)
  // ============================
  zerodha: 'Investments',
  groww: 'Investments',
  angelone: 'Investments',
  angel: 'Investments',
  upstox: 'Investments',
  coin: 'Investments',
  kuvera: 'Investments',
  etmoney: 'Investments',
  paytmmoney: 'Investments',
  smallcase: 'Investments',
  lic: 'Investments',
  sbilife: 'Investments',
  hdfclife: 'Investments',
  icicipru: 'Investments',
  phonepewealth: 'Investments',
  mutualfund: 'Investments',
  sip: 'Investments',
  fd: 'Investments',
  fixeddeposit: 'Investments',
  rd: 'Investments',
  recurringdeposit: 'Investments',
  ppf: 'Investments',
  nps: 'Investments',
  gold: 'Investments',
  investment: 'Investments',
  trading: 'Investments',
  stock: 'Investments',
  share: 'Investments',
  demat: 'Investments',
  equity: 'Investments',
  bond: 'Investments',
  nsc: 'Investments',
  sovereign: 'Investments',
  sgb: 'Investments',
  mf: 'Investments',
  elss: 'Investments',
  sukanya: 'Investments',
  kvp: 'Investments',
  hdfcmf: 'Investments',
  sbimf: 'Investments',
  icicimf: 'Investments',
  axismf: 'Investments',
  kotakmf: 'Investments',
  dsp: 'Investments',
  nippon: 'Investments',
  tata: 'Investments',
  birla: 'Investments',
  aditya: 'Investments',
  motilal: 'Investments',
  idfc: 'Investments',
  mirae: 'Investments',
  edelweiss: 'Investments',
  '5paisa': 'Investments',
  fivepaisa: 'Investments',
  iifl: 'Investments',
  sharekhan: 'Investments',
  icicidir: 'Investments',
  hdfcsec: 'Investments',
  kotak: 'Investments',

  // ============================
  // Rent & EMI (30+ entries)
  // ============================
  rent: 'Rent & EMI',
  emi: 'Rent & EMI',
  loan: 'Rent & EMI',
  mortgage: 'Rent & EMI',
  housing: 'Rent & EMI',
  apartment: 'Rent & EMI',
  flat: 'Rent & EMI',
  homeloan: 'Rent & EMI',
  carloan: 'Rent & EMI',
  personalloan: 'Rent & EMI',
  bajajfinance: 'Rent & EMI',
  bajajfinserv: 'Rent & EMI',
  hdfcltd: 'Rent & EMI',
  sbihome: 'Rent & EMI',
  lichfl: 'Rent & EMI',
  pnbhousing: 'Rent & EMI',
  indiabulls: 'Rent & EMI',
  tatahousing: 'Rent & EMI',
  lnt: 'Rent & EMI',
  godrej: 'Rent & EMI',
  dewan: 'Rent & EMI',
  canfin: 'Rent & EMI',
  gruh: 'Rent & EMI',
  repayment: 'Rent & EMI',
  installment: 'Rent & EMI',
  equated: 'Rent & EMI',
  monthly: 'Rent & EMI',
  tenancy: 'Rent & EMI',
  lease: 'Rent & EMI',
  landlord: 'Rent & EMI',
  maintenance: 'Rent & EMI',
  society: 'Rent & EMI',
  homefc: 'Rent & EMI',
  fullerton: 'Rent & EMI',
  manappuram: 'Rent & EMI',
  muthoot: 'Rent & EMI',

  // ============================
  // Groceries (40+ entries)
  // ============================
  bigbasket: 'Groceries',
  blinkit: 'Groceries',
  zepto: 'Groceries',
  jiomart: 'Groceries',
  dmart: 'Groceries',
  dunzo: 'Groceries',
  reliancefresh: 'Groceries',
  moresupermarket: 'Groceries',
  starbazaar: 'Groceries',
  spencers: 'Groceries',
  instamart: 'Groceries',
  naturesbasket: 'Groceries',
  grocery: 'Groceries',
  supermarket: 'Groceries',
  kirana: 'Groceries',
  vegetables: 'Groceries',
  fruits: 'Groceries',
  milk: 'Groceries',
  dairy: 'Groceries',
  provision: 'Groceries',
  ration: 'Groceries',
  amul: 'Groceries',
  mother: 'Groceries',
  nandini: 'Groceries',
  aavin: 'Groceries',
  verka: 'Groceries',
  milma: 'Groceries',
  country: 'Groceries',
  organic: 'Groceries',
  nilgiris: 'Groceries',
  heritage: 'Groceries',
  milkbasket: 'Groceries',
  dailyninja: 'Groceries',
  supr: 'Groceries',
  grofers: 'Groceries',
  easyday: 'Groceries',
  hypermarket: 'Groceries',
  hypercity: 'Groceries',
  spar: 'Groceries',
  metrocash: 'Groceries',
  lulu: 'Groceries',
  ratnadeep: 'Groceries',

  // ============================
  // Income / Salary (20+ entries)
  // ============================
  salary: 'Income',
  wages: 'Income',
  bonus: 'Income',
  incentive: 'Income',
  reimbursement: 'Income',
  stipend: 'Income',
  freelance: 'Income',
  consultancy: 'Income',
  honorarium: 'Income',
  commission: 'Income',
  dividend: 'Income',
  interest: 'Income',
  cashback: 'Income',
  refund: 'Income',
  reversal: 'Income',
  paymentreceived: 'Income',
  credited: 'Income',
  payout: 'Income',
  earnings: 'Income',
  arrears: 'Income',

  // ============================
  // Payment Platforms (no specific category)
  // ============================
  paytm: 'Others',
  phonepe: 'Others',
  gpay: 'Others',
  googlepay: 'Others',
  cred: 'Others',
  slice: 'Others',
  simpl: 'Others',
  lazypay: 'Others',
  freecharge: 'Others',
  mobikwik: 'Others',
  amazonpay: 'Others',
  bhim: 'Others',
  atm: 'Others',
  cash: 'Others',
  withdrawal: 'Others',
  transfer: 'Others',
  neft: 'Others',
  imps: 'Others',
  rtgs: 'Others',
};

/**
 * Keyword lists for secondary matching.
 * These contain broader terms that indicate a category.
 */
export const CATEGORY_KEYWORDS: Record<CategoryName, string[]> = {
  'Food & Dining': [
    'restaurant', 'cafe', 'food', 'dining', 'eat', 'meal', 'biryani',
    'pizza', 'burger', 'snack', 'tea', 'coffee', 'bakery', 'sweet',
    'hotel', 'dhaba', 'canteen', 'mess', 'tiffin', 'catering',
    'bar', 'pub', 'lounge', 'grill', 'kitchen', 'cook',
  ],
  Transport: [
    'cab', 'taxi', 'auto', 'rickshaw', 'flight', 'airline', 'railway',
    'train', 'bus', 'petrol', 'diesel', 'fuel', 'parking', 'toll',
    'travel', 'trip', 'ride', 'commute', 'transit',
  ],
  Shopping: [
    'mall', 'store', 'retail', 'clothing', 'shoes', 'electronics',
    'furniture', 'jewellery', 'jewelry', 'cosmetics', 'fashion',
    'garment', 'textile', 'boutique', 'showroom', 'mart',
  ],
  'Bills & Utilities': [
    'electricity', 'water', 'gas', 'phone', 'mobile', 'internet',
    'wifi', 'broadband', 'bill', 'recharge', 'dth', 'postpaid',
    'prepaid', 'landline', 'cylinder', 'lpg', 'piped',
  ],
  Entertainment: [
    'movie', 'cinema', 'theatre', 'concert', 'gaming', 'game',
    'subscription', 'stream', 'show', 'event', 'festival', 'ticket',
  ],
  Health: [
    'hospital', 'doctor', 'medical', 'pharmacy', 'medicine', 'clinic',
    'dental', 'gym', 'fitness', 'yoga', 'wellness', 'spa',
    'diagnostic', 'lab', 'pathology', 'surgery', 'treatment',
  ],
  Education: [
    'school', 'college', 'university', 'tuition', 'course', 'book',
    'library', 'exam', 'coaching', 'institute', 'academy',
    'tutorial', 'class', 'certification', 'training', 'workshop',
  ],
  Income: [
    'salary', 'wages', 'bonus', 'incentive', 'reimbursement',
    'income', 'credit', 'refund', 'cashback', 'dividend', 'interest',
    'freelance', 'payment received', 'payout', 'earnings',
  ],
  Investments: [
    'sip', 'mutual fund', 'stock', 'share', 'fd', 'fixed deposit',
    'ppf', 'nps', 'gold', 'investment', 'trading', 'demat',
    'equity', 'bond', 'insurance', 'policy', 'premium',
  ],
  'Rent & EMI': [
    'rent', 'emi', 'loan', 'mortgage', 'housing', 'apartment',
    'flat', 'installment', 'repayment', 'lease', 'tenancy',
    'maintenance', 'society',
  ],
  Groceries: [
    'grocery', 'supermarket', 'kirana', 'vegetables', 'fruits',
    'milk', 'dairy', 'provision', 'ration', 'organic',
  ],
  Others: [],
};

/**
 * Regex patterns for common transaction prefixes/formats.
 */
export const TRANSACTION_PATTERNS: Array<{
  pattern: RegExp;
  category: CategoryName;
  label: string;
}> = [
  { pattern: /^upi[/-]/i, category: 'Others', label: 'UPI Payment' },
  { pattern: /^neft[/-]/i, category: 'Others', label: 'NEFT Transfer' },
  { pattern: /^imps[/-]/i, category: 'Others', label: 'IMPS Transfer' },
  { pattern: /^rtgs[/-]/i, category: 'Others', label: 'RTGS Transfer' },
  { pattern: /^(bil|bpay)[/-]/i, category: 'Bills & Utilities', label: 'Bill Payment' },
  { pattern: /^pos[/-\s]/i, category: 'Shopping', label: 'POS Purchase' },
  { pattern: /^atm[/-\s]/i, category: 'Others', label: 'ATM Withdrawal' },
  { pattern: /^ecs[/-]/i, category: 'Rent & EMI', label: 'ECS Payment' },
  { pattern: /^nach[/-]/i, category: 'Rent & EMI', label: 'NACH Mandate' },
  { pattern: /\bsip\b/i, category: 'Investments', label: 'SIP Investment' },
  { pattern: /\bmutual\s*fund/i, category: 'Investments', label: 'Mutual Fund' },
  { pattern: /\b(fd|fixed\s*deposit)/i, category: 'Investments', label: 'Fixed Deposit' },
  { pattern: /\b(rd|recurring\s*deposit)/i, category: 'Investments', label: 'Recurring Deposit' },
  { pattern: /\binsurance\b/i, category: 'Investments', label: 'Insurance' },
  { pattern: /\bpremium\b/i, category: 'Investments', label: 'Insurance Premium' },
  { pattern: /\bloan\s*(emi|repay)/i, category: 'Rent & EMI', label: 'Loan EMI' },
  { pattern: /\b(home|car|personal)\s*loan/i, category: 'Rent & EMI', label: 'Loan Payment' },
  { pattern: /\brent\b/i, category: 'Rent & EMI', label: 'Rent Payment' },
  { pattern: /\bsalary\b/i, category: 'Income', label: 'Salary' },
];
